language: node_js
sudo: false
node_js:
  - "7.0"
install:
  - npm install
script:
  - npm run cover && codecov

deploy:
  provider: npm
  email: ken.vizztech@gmail.com

  on:
    tags: true
    repo: vip30/vue-local-storage-decorator
    branch: master
    node: '7.0'
